secretGenerator:
- name: registry-env-secret
  envs:
  - .env.secrets

generators:
  - registry-tls-secret.yaml

resources:
- namespace.yaml
- pv.yaml
- pvc.yaml
- deployment.yaml
- svc.yaml

namespace: registry
