apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 14Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Retain the volume after the PVC is deleted
  storageClassName: local-storage  # must match PVC definition
  hostPath:
    path: /mnt/k8s/registry
    type: DirectoryOrCreate  # create dir if needed
