apiVersion: builtin
kind: SecretGenerator
metadata:
  name: registry-tls-secret
behavior: create
files:
  - tls.crt=certs/registry.crt
  - tls.key=certs/registry.key
type: kubernetes.io/tls
options:
  disableNameSuffixHash: true
