apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-cleaner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-cleaner-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-cleaner-binding
subjects:
- kind: ServiceAccount
  name: node-cleaner
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: node-cleaner-role
  apiGroup: rbac.authorization.k8s.io
